# Generated by Django 6.0.5 on 2026-06-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmaveex',
            name='veex_alarm_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID API VeEX'),
        ),
    ]
