# Generated by Django 6.0.5 on 2026-06-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0002_alarmaveex_veex_alarm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='veex_alarm_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID API VeEX'),
        ),
    ]
