# Generated by Django 6.0.5 on 2026-06-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0003_eventlog_veex_alarm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmaveex',
            name='archivo_sor',
            field=models.FileField(blank=True, null=True, upload_to='trazas_padre/', verbose_name='Archivo .sor Local'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='archivo_sor',
            field=models.FileField(blank=True, null=True, upload_to='trazas_logs/', verbose_name='Archivo .sor Local'),
        ),
    ]
