# Generated by Django 6.0.5 on 2026-06-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0004_alarmaveex_archivo_sor_eventlog_archivo_sor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrazaOnDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=150, verbose_name='Nombre de Ruta')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('status', models.CharField(default='Pending', max_length=50, verbose_name='Estado de Solicitud')),
                ('veex_on_demand_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Tarea VeEX')),
                ('archivo_sor', models.FileField(blank=True, null=True, upload_to='trazas_ondemand/', verbose_name='Archivo .sor Descargado')),
                ('distance_km', models.FloatField(blank=True, null=True, verbose_name='Distancia Reportada (Km)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
            ],
            options={
                'verbose_name': 'Traza Bajo Demanda',
                'verbose_name_plural': 'Trazas Bajo Demanda',
                'db_table': 'mon_trazas_ondemand',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
