# Generated by Django 6.0.5 on 2026-06-08 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0005_trazaondemand'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUmbral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perfil', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Perfil')),
                ('splice_loss', models.FloatField(default=0.1, verbose_name='Pérdida por Empalme (dB)')),
                ('connector_loss', models.FloatField(default=0.5, verbose_name='Pérdida por Conector (dB)')),
                ('reflectance', models.FloatField(default=-45.0, verbose_name='Reflectancia (dB)')),
                ('attenuation', models.FloatField(default=0.5, verbose_name='Atenuación (dB/km)')),
                ('end_of_fiber', models.FloatField(default=3.0, verbose_name='Fin de Fibra (dB)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Umbrales',
                'verbose_name_plural': 'Perfiles de Umbrales',
                'db_table': 'inv_perfil_umbrales',
            },
        ),
        migrations.AddField(
            model_name='ruta',
            name='perfil_umbral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='mapas.perfilumbral', verbose_name='Perfil de Umbrales'),
        ),
    ]
