# Generated by Django 6.0.5 on 2026-06-09 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0006_perfilumbral_ruta_perfil_umbral'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilumbral',
            name='atenuacion_critical_min',
            field=models.FloatField(default=5.0, verbose_name='Atenuación Critical (Min dB)'),
        ),
        migrations.AddField(
            model_name='perfilumbral',
            name='atenuacion_major_min',
            field=models.FloatField(default=3.0, verbose_name='Atenuación Major (Min dB)'),
        ),
        migrations.AddField(
            model_name='perfilumbral',
            name='atenuacion_minor_min',
            field=models.FloatField(default=1.0, verbose_name='Atenuación Minor (Min dB)'),
        ),
        migrations.AddField(
            model_name='perfilumbral',
            name='nivel_minimo_corte_db',
            field=models.FloatField(default=-15.0, verbose_name='Nivel mínimo para Corte (dB)'),
        ),
        migrations.CreateModel(
            name='TrazaReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de Referencia')),
                ('archivo_sor', models.FileField(upload_to='trazas_referencia/', verbose_name='Archivo .sor de Referencia')),
                ('distancia_km', models.FloatField(blank=True, null=True, verbose_name='Distancia Total (Km)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activa', models.BooleanField(default=True, verbose_name='Referencia Principal')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazas_referencia', to='mapas.ruta', verbose_name='Ruta Asociada')),
            ],
            options={
                'verbose_name': 'Traza de Referencia',
                'verbose_name_plural': 'Trazas de Referencia',
                'db_table': 'mon_trazas_referencia',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoProactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_falla', models.CharField(max_length=100, verbose_name='Tipo de Falla (Atenuación / Corte)')),
                ('severidad', models.CharField(max_length=50, verbose_name='Severidad')),
                ('distancia_falla_m', models.FloatField(verbose_name='Distancia de la Falla (metros)')),
                ('desviacion_db', models.FloatField(blank=True, null=True, verbose_name='Desviación (dB)')),
                ('archivo_sor_actual', models.FileField(upload_to='trazas_proactivas/', verbose_name='Archivo .sor Analizado')),
                ('fecha_diagnostico', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Diagnóstico')),
                ('estado', models.CharField(default='Abierta', max_length=50, verbose_name='Estado de Alarma')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_proactivos', to='mapas.ruta', verbose_name='Ruta Asociada')),
                ('traza_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapas.trazareferencia', verbose_name='Referencia Utilizada')),
            ],
            options={
                'verbose_name': 'Diagnóstico Proactivo',
                'verbose_name_plural': 'Diagnósticos Proactivos',
                'db_table': 'mon_diagnostico_proactivo',
                'ordering': ['-fecha_diagnostico'],
            },
        ),
    ]
