# Generated by Django 6.0.5 on 2026-06-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0007_perfilumbral_atenuacion_critical_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilumbral',
            name='nivel_minimo_corte_db',
        ),
        migrations.AddField(
            model_name='perfilumbral',
            name='margen_corte_fibra_db',
            field=models.FloatField(default=2.0, verbose_name='Margen sobre piso de ruido para Corte (dB)'),
        ),
    ]
