# Generated by Django 6.0.5 on 2026-06-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0008_remove_perfilumbral_nivel_minimo_corte_db_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariofibra',
            name='circuito',
        ),
        migrations.RemoveField(
            model_name='inventariofibra',
            name='empalme',
        ),
        migrations.RemoveField(
            model_name='inventariofibra',
            name='patch',
        ),
        migrations.RemoveField(
            model_name='inventariofibra',
            name='tipo_fibra',
        ),
        migrations.AddField(
            model_name='inventariofibra',
            name='tipo_conector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Conector'),
        ),
        migrations.AlterField(
            model_name='inventariofibra',
            name='estado',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Ocupado', 'Ocupado'), ('Reservado', 'Reservado')], default='Libre', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='inventariofibra',
            name='nombre_fibra',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre/Descripción (Si está ocupada/reservada)'),
        ),
    ]
