# Generated by Django 6.0.5 on 2026-06-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0009_remove_inventariofibra_circuito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='tipo_conexion',
        ),
    ]
