# Generated by Django 6.0.5 on 2026-06-19 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0010_remove_reserva_tipo_conexion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioodf',
            name='troncal',
        ),
    ]
