# Generated by Django 6.0.5 on 2026-06-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0011_remove_inventarioodf_troncal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepuertoodf',
            name='circuito_servicio',
        ),
    ]
