# Generated by Django 6.0.5 on 2026-07-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0012_remove_detallepuertoodf_circuito_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['nombre'], 'permissions': [('can_view_reports', 'Puede ver Reportes (Dashboard/Ranking)')], 'verbose_name': 'Ruta de Fibra', 'verbose_name_plural': 'Rutas de Fibra'},
        ),
    ]
