# Generated by Django 6.0.5 on 2026-07-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0014_alter_ruta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepuertoodf',
            options={'ordering': ['odf_obj', 'puerto_odf'], 'verbose_name': 'Detalle de Puerto ODF', 'verbose_name_plural': 'Detalle de Puertos ODF'},
        ),
        migrations.AlterUniqueTogether(
            name='detallepuertoodf',
            unique_together={('odf_obj', 'puerto_odf')},
        ),
    ]
