# Generated by Django 6.0.5 on 2026-07-17 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0015_alter_detallepuertoodf_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CableFibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=180)),
                ('capacidad_fibras', models.PositiveIntegerField()),
                ('tipo_fibra', models.CharField(blank=True, max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('longitud_documentada_m', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('OPERATIVO', 'Operativo'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('RETIRADO', 'Retirado'), ('POR_CONFIRMAR', 'Por confirmar')], default='POR_CONFIRMAR', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inv_cables_fibra',
            },
        ),
        migrations.CreateModel(
            name='CoordenadaTramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
            options={
                'db_table': 'inv_cables_tramos_coordenadas',
                'ordering': ['tramo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ElementoPlantaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MUFA', 'Mufa'), ('CAMARA', 'Cámara'), ('POSTE', 'Poste'), ('RESERVA', 'Reserva'), ('SPLITTER', 'Splitter'), ('CAJA_EMPALME', 'Caja de empalme'), ('CAJA_TERMINAL', 'Caja terminal'), ('CRUCE', 'Cruce'), ('DUCTO', 'Ducto'), ('PUNTO_REFERENCIA', 'Punto de referencia'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=40)),
                ('tipo_original_cliente', models.CharField(blank=True, max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre', models.CharField(max_length=180)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('orden_en_ruta', models.PositiveIntegerField(blank=True, null=True)),
                ('progresiva_m', models.FloatField(blank=True, null=True)),
                ('reserva_m', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(default='POR_CONFIRMAR', max_length=30)),
                ('atributos', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'inv_elementos_planta_externa',
                'ordering': ['ruta', 'orden_en_ruta', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmpalmeFibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeja', models.CharField(blank=True, max_length=50)),
                ('posicion', models.CharField(blank=True, max_length=50)),
                ('perdida_db', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(default='POR_CONFIRMAR', max_length=30)),
            ],
            options={
                'db_table': 'inv_fibras_empalmes',
            },
        ),
        migrations.CreateModel(
            name='FibraCable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('RESERVADO', 'Reservado'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('POR_CONFIRMAR', 'Por confirmar')], default='POR_CONFIRMAR', max_length=30)),
                ('servicio', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'inv_cables_fibras',
                'ordering': ['cable', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='LoteImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(max_length=80)),
                ('archivo_origen', models.CharField(max_length=255)),
                ('hash_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('COMPLETADO_CON_ERRORES', 'Completado con errores'), ('FALLIDO', 'Fallido'), ('REVERTIDO', 'Revertido')], db_index=True, default='PENDIENTE', max_length=30)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('filas_creadas', models.PositiveIntegerField(default=0)),
                ('filas_actualizadas', models.PositiveIntegerField(default=0)),
                ('filas_rechazadas', models.PositiveIntegerField(default=0)),
                ('detalle_errores', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_lotes_importacion',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RackFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('unidades_rack', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=30)),
            ],
            options={
                'db_table': 'inv_racks_fisicos',
                'ordering': ['sala__hub_site__nombre', 'sala__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SalaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(default='ACTIVO', max_length=30)),
            ],
            options={
                'db_table': 'inv_salas_tecnicas',
                'ordering': ['hub_site__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SiteAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=150)),
                ('fuente', models.CharField(default='KML/KMZ', max_length=150)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('distancia_coincidencia_m', models.FloatField(blank=True, null=True)),
                ('validado', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'inv_sites_alias',
            },
        ),
        migrations.CreateModel(
            name='TerminacionFibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extremo', models.CharField(choices=[('A', 'Extremo A'), ('B', 'Extremo B')], max_length=1)),
                ('tipo_conector', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'inv_fibras_terminaciones',
            },
        ),
        migrations.CreateModel(
            name='TramoCable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.PositiveIntegerField()),
                ('origen_descripcion', models.CharField(blank=True, max_length=180)),
                ('destino_descripcion', models.CharField(blank=True, max_length=180)),
                ('tipo_trazado', models.CharField(choices=[('AEREO', 'Aéreo'), ('SUBTERRANEO', 'Subterráneo'), ('DUCTO', 'Ducto'), ('MIXTO', 'Mixto'), ('POR_CONFIRMAR', 'Por confirmar')], default='POR_CONFIRMAR', max_length=30)),
                ('distancia_m', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(default='POR_CONFIRMAR', max_length=30)),
            ],
            options={
                'db_table': 'inv_cables_tramos',
                'ordering': ['cable', 'secuencia'],
            },
        ),
        migrations.AlterModelOptions(
            name='detallepuertoodf',
            options={'ordering': ['odf', 'puerto_odf'], 'verbose_name': 'Detalle de Puerto ODF', 'verbose_name_plural': 'Detalle de Puertos ODF'},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['nombre'], 'permissions': [('can_view_reports', 'Puede ver Reportes (Dashboard/Ranking)')], 'verbose_name': 'Ruta de Fibra', 'verbose_name_plural': 'Rutas de Fibra'},
        ),
        migrations.AlterUniqueTogether(
            name='detallepuertoodf',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alarmaveex',
            name='ruta_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarmas_veex', to='mapas.ruta', verbose_name='Ruta relacionada'),
        ),
        migrations.AddField(
            model_name='alarmaveex',
            name='timestamp_evento',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='coordenadaruta',
            name='tramo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordenadas', to='mapas.inventariotramo', verbose_name='Tramo relacionado'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='ruta_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_alarmas', to='mapas.ruta', verbose_name='Ruta relacionada'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='timestamp_evento',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='idruta',
            name='ruta_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identificadores_onmsi', to='mapas.ruta', verbose_name='Ruta relacionada'),
        ),
        migrations.AddField(
            model_name='inventarioodf',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='inventarioodf',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tramo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='mapas.inventariotramo', verbose_name='Tramo relacionado'),
        ),
        migrations.AddField(
            model_name='trazaondemand',
            name='ruta_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_on_demand', to='mapas.ruta', verbose_name='Ruta relacionada'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_logs', to='mapas.alarmaveex', verbose_name='Incidente Padre'),
        ),
        migrations.AlterField(
            model_name='idruta',
            name='id_onmsi',
            field=models.IntegerField(db_index=True, verbose_name='ID ONMSI'),
        ),
        migrations.AddIndex(
            model_name='alarmaveex',
            index=models.Index(fields=['status', '-fecha_registro'], name='ix_alarma_status_fecha'),
        ),
        migrations.AddIndex(
            model_name='alarmaveex',
            index=models.Index(fields=['alarm_level', '-fecha_registro'], name='ix_alarma_nivel_fecha'),
        ),
        migrations.AddIndex(
            model_name='alarmaveex',
            index=models.Index(fields=['alarm_type', '-fecha_registro'], name='ix_alarma_tipo_fecha'),
        ),
        migrations.AddIndex(
            model_name='alarmaveex',
            index=models.Index(fields=['device_serial', 'port'], name='ix_alarma_equipo_puerto'),
        ),
        migrations.AddIndex(
            model_name='alarmaveex',
            index=models.Index(fields=['route_name'], name='ix_alarma_ruta_texto'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['status', '-fecha_registro'], name='ix_log_status_fecha'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['route_name', '-fecha_registro'], name='ix_log_ruta_fecha'),
        ),
        migrations.AddConstraint(
            model_name='alarmaveex',
            constraint=models.UniqueConstraint(condition=models.Q(('veex_alarm_id__isnull', False)), fields=('veex_alarm_id',), name='uq_alarma_veex_id'),
        ),
        migrations.AddConstraint(
            model_name='alarmaveex',
            constraint=models.CheckConstraint(condition=models.Q(('distance__isnull', True), ('distance__gte', 0), _connector='OR'), name='ck_alarma_distancia_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='coordenadaruta',
            constraint=models.CheckConstraint(condition=models.Q(('latitud__gte', -90), ('latitud__lte', 90)), name='ck_coordenada_ruta_latitud'),
        ),
        migrations.AddConstraint(
            model_name='coordenadaruta',
            constraint=models.CheckConstraint(condition=models.Q(('longitud__gte', -180), ('longitud__lte', 180)), name='ck_coordenada_ruta_longitud'),
        ),
        migrations.AddConstraint(
            model_name='detallepuertoodf',
            constraint=models.UniqueConstraint(fields=('odf_obj', 'puerto_odf'), name='uq_puerto_odf_numero'),
        ),
        migrations.AddConstraint(
            model_name='idruta',
            constraint=models.UniqueConstraint(fields=('id_onmsi',), name='uq_idruta_onmsi'),
        ),
        migrations.AddConstraint(
            model_name='idruta',
            constraint=models.UniqueConstraint(condition=models.Q(('ruta_obj__isnull', False)), fields=('ruta_obj',), name='uq_idruta_ruta_obj'),
        ),
        migrations.AddConstraint(
            model_name='inventariotramo',
            constraint=models.CheckConstraint(condition=models.Q(('distancia_m__isnull', True), ('distancia_m__gte', 0), _connector='OR'), name='ck_tramo_distancia_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='inventariotramo',
            constraint=models.CheckConstraint(condition=models.Q(('mufas__isnull', True), ('mufas__gte', 0), _connector='OR'), name='ck_tramo_mufas_no_negativas'),
        ),
        migrations.AddConstraint(
            model_name='inventariotramo',
            constraint=models.CheckConstraint(condition=models.Q(('splitters__isnull', True), ('splitters__gte', 0), _connector='OR'), name='ck_tramo_splitters_no_negativos'),
        ),
        migrations.AddConstraint(
            model_name='inventariotramo',
            constraint=models.CheckConstraint(condition=models.Q(('reservas_m__isnull', True), ('reservas_m__gte', 0), _connector='OR'), name='ck_tramo_reserva_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='inventariotramo',
            constraint=models.CheckConstraint(condition=models.Q(('hilos_ocupados__isnull', True), ('hilos_ocupados__gte', 0), _connector='OR'), name='ck_tramo_hilos_ocupados'),
        ),
        migrations.AddConstraint(
            model_name='inventariotramo',
            constraint=models.CheckConstraint(condition=models.Q(('hilos_libres__isnull', True), ('hilos_libres__gte', 0), _connector='OR'), name='ck_tramo_hilos_libres'),
        ),
        migrations.AddConstraint(
            model_name='trazareferencia',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('ruta',), name='uq_traza_referencia_activa_ruta'),
        ),
        migrations.AddField(
            model_name='cablefibra',
            name='destino_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cables_destino', to='mapas.hubsite'),
        ),
        migrations.AddField(
            model_name='cablefibra',
            name='origen_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cables_origen', to='mapas.hubsite'),
        ),
        migrations.AddField(
            model_name='cablefibra',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cables', to='mapas.ruta'),
        ),
        migrations.AddField(
            model_name='elementoplantaexterna',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_planta', to='mapas.ruta'),
        ),
        migrations.AddField(
            model_name='empalmefibra',
            name='elemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empalmes', to='mapas.elementoplantaexterna'),
        ),
        migrations.AddField(
            model_name='fibracable',
            name='cable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fibras', to='mapas.cablefibra'),
        ),
        migrations.AddField(
            model_name='empalmefibra',
            name='fibra_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empalmes_entrada', to='mapas.fibracable'),
        ),
        migrations.AddField(
            model_name='empalmefibra',
            name='fibra_salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empalmes_salida', to='mapas.fibracable'),
        ),
        migrations.AddField(
            model_name='inventariofibra',
            name='fibra_fisica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_legacy', to='mapas.fibracable', verbose_name='Fibra física normalizada'),
        ),
        migrations.AddField(
            model_name='loteimportacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_importacion_fibergenius', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fibracable',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fibras_cable', to='mapas.loteimportacion'),
        ),
        migrations.AddField(
            model_name='empalmefibra',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empalmes_fibra', to='mapas.loteimportacion'),
        ),
        migrations.AddField(
            model_name='elementoplantaexterna',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_planta', to='mapas.loteimportacion'),
        ),
        migrations.AddField(
            model_name='coordenadatramo',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordenadas_tramo', to='mapas.loteimportacion'),
        ),
        migrations.AddField(
            model_name='cablefibra',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cables', to='mapas.loteimportacion'),
        ),
        migrations.AddField(
            model_name='inventariofibra',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fibras_legacy', to='mapas.loteimportacion'),
        ),
        migrations.AddField(
            model_name='inventarioodf',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odfs', to='mapas.loteimportacion'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='mapas.loteimportacion'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('reserva_m__isnull', True), ('reserva_m__gte', 0), _connector='OR'), name='ck_reserva_m_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('latitud__gte', -90), ('latitud__lte', 90)), name='ck_reserva_latitud'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('longitud__gte', -180), ('longitud__lte', 180)), name='ck_reserva_longitud'),
        ),
        migrations.AddField(
            model_name='rackfisico',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='mapas.loteimportacion'),
        ),
        migrations.AddField(
            model_name='inventarioodf',
            name='rack_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odfs', to='mapas.rackfisico', verbose_name='Rack relacionado'),
        ),
        migrations.AddConstraint(
            model_name='inventarioodf',
            constraint=models.UniqueConstraint(condition=models.Q(('rack_obj__isnull', False)), fields=('rack_obj', 'odf'), name='uq_odf_rack_nombre'),
        ),
        migrations.AddConstraint(
            model_name='inventarioodf',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad_puertos__isnull', True), ('capacidad_puertos__gte', 0), _connector='OR'), name='ck_odf_capacidad_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='inventarioodf',
            constraint=models.CheckConstraint(condition=models.Q(('puertos_ocupados__isnull', True), ('puertos_ocupados__gte', 0), _connector='OR'), name='ck_odf_ocupados_no_negativos'),
        ),
        migrations.AddConstraint(
            model_name='inventarioodf',
            constraint=models.CheckConstraint(condition=models.Q(('puertos_libres__isnull', True), ('puertos_libres__gte', 0), _connector='OR'), name='ck_odf_libres_no_negativos'),
        ),
        migrations.AddField(
            model_name='salatecnica',
            name='hub_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salas', to='mapas.hubsite'),
        ),
        migrations.AddField(
            model_name='salatecnica',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas', to='mapas.loteimportacion'),
        ),
        migrations.AddField(
            model_name='rackfisico',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racks', to='mapas.salatecnica'),
        ),
        migrations.AddField(
            model_name='sitealias',
            name='hub_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='mapas.hubsite'),
        ),
        migrations.AddField(
            model_name='sitealias',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases_site', to='mapas.loteimportacion'),
        ),
        migrations.AddField(
            model_name='terminacionfibra',
            name='fibra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminaciones', to='mapas.fibracable'),
        ),
        migrations.AddField(
            model_name='terminacionfibra',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminaciones_fibra', to='mapas.loteimportacion'),
        ),
        migrations.AddField(
            model_name='terminacionfibra',
            name='puerto_odf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminaciones_fibra', to='mapas.detallepuertoodf'),
        ),
        migrations.AddField(
            model_name='tramocable',
            name='cable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='mapas.cablefibra'),
        ),
        migrations.AddField(
            model_name='tramocable',
            name='destino_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramos_cable_destino', to='mapas.hubsite'),
        ),
        migrations.AddField(
            model_name='tramocable',
            name='inventario_tramo_legacy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramo_cable_normalizado', to='mapas.inventariotramo'),
        ),
        migrations.AddField(
            model_name='tramocable',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramos_cable', to='mapas.loteimportacion'),
        ),
        migrations.AddField(
            model_name='tramocable',
            name='origen_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramos_cable_origen', to='mapas.hubsite'),
        ),
        migrations.AddField(
            model_name='elementoplantaexterna',
            name='tramo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos', to='mapas.tramocable'),
        ),
        migrations.AddField(
            model_name='coordenadatramo',
            name='tramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenadas', to='mapas.tramocable'),
        ),
        migrations.AddConstraint(
            model_name='fibracable',
            constraint=models.UniqueConstraint(fields=('cable', 'numero'), name='uq_fibra_cable_numero'),
        ),
        migrations.AddConstraint(
            model_name='fibracable',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gt', 0)), name='ck_fibra_numero_positivo'),
        ),
        migrations.AddConstraint(
            model_name='empalmefibra',
            constraint=models.UniqueConstraint(fields=('elemento', 'fibra_entrada', 'fibra_salida'), name='uq_empalme_elemento_fibras'),
        ),
        migrations.AddConstraint(
            model_name='empalmefibra',
            constraint=models.CheckConstraint(condition=models.Q(('fibra_entrada__lt', models.F('fibra_salida'))), name='ck_empalme_fibras_distintas'),
        ),
        migrations.AddConstraint(
            model_name='empalmefibra',
            constraint=models.CheckConstraint(condition=models.Q(('perdida_db__isnull', True), ('perdida_db__gte', 0), _connector='OR'), name='ck_empalme_perdida_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='cablefibra',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad_fibras__gt', 0)), name='ck_cable_capacidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='cablefibra',
            constraint=models.CheckConstraint(condition=models.Q(('longitud_documentada_m__isnull', True), ('longitud_documentada_m__gte', 0), _connector='OR'), name='ck_cable_longitud_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='salatecnica',
            constraint=models.UniqueConstraint(fields=('hub_site', 'nombre'), name='uq_sala_hub_nombre'),
        ),
        migrations.AddConstraint(
            model_name='rackfisico',
            constraint=models.UniqueConstraint(fields=('sala', 'nombre'), name='uq_rack_sala_nombre'),
        ),
        migrations.AddConstraint(
            model_name='sitealias',
            constraint=models.UniqueConstraint(fields=('hub_site', 'alias', 'fuente'), name='uq_site_alias_fuente'),
        ),
        migrations.AddConstraint(
            model_name='sitealias',
            constraint=models.CheckConstraint(condition=models.Q(('distancia_coincidencia_m__isnull', True), ('distancia_coincidencia_m__gte', 0), _connector='OR'), name='ck_alias_distancia_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='terminacionfibra',
            constraint=models.UniqueConstraint(fields=('fibra', 'extremo'), name='uq_terminacion_fibra_extremo'),
        ),
        migrations.AddConstraint(
            model_name='terminacionfibra',
            constraint=models.UniqueConstraint(fields=('puerto_odf',), name='uq_terminacion_puerto_odf'),
        ),
        migrations.AddConstraint(
            model_name='tramocable',
            constraint=models.UniqueConstraint(fields=('cable', 'secuencia'), name='uq_tramo_cable_secuencia'),
        ),
        migrations.AddConstraint(
            model_name='tramocable',
            constraint=models.CheckConstraint(condition=models.Q(('distancia_m__isnull', True), ('distancia_m__gte', 0), _connector='OR'), name='ck_tramo_cable_distancia'),
        ),
        migrations.AddConstraint(
            model_name='elementoplantaexterna',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo__isnull', False), models.Q(('codigo', ''), _negated=True)), fields=('codigo',), name='uq_elemento_planta_codigo'),
        ),
        migrations.AddConstraint(
            model_name='elementoplantaexterna',
            constraint=models.CheckConstraint(condition=models.Q(('latitud__gte', -90), ('latitud__lte', 90)), name='ck_elemento_latitud'),
        ),
        migrations.AddConstraint(
            model_name='elementoplantaexterna',
            constraint=models.CheckConstraint(condition=models.Q(('longitud__gte', -180), ('longitud__lte', 180)), name='ck_elemento_longitud'),
        ),
        migrations.AddConstraint(
            model_name='elementoplantaexterna',
            constraint=models.CheckConstraint(condition=models.Q(('progresiva_m__isnull', True), ('progresiva_m__gte', 0), _connector='OR'), name='ck_elemento_progresiva'),
        ),
        migrations.AddConstraint(
            model_name='elementoplantaexterna',
            constraint=models.CheckConstraint(condition=models.Q(('reserva_m__isnull', True), ('reserva_m__gte', 0), _connector='OR'), name='ck_elemento_reserva'),
        ),
        migrations.AddConstraint(
            model_name='coordenadatramo',
            constraint=models.UniqueConstraint(fields=('tramo', 'orden'), name='uq_coord_tramo_orden'),
        ),
        migrations.AddConstraint(
            model_name='coordenadatramo',
            constraint=models.CheckConstraint(condition=models.Q(('latitud__gte', -90), ('latitud__lte', 90)), name='ck_coord_tramo_latitud'),
        ),
        migrations.AddConstraint(
            model_name='coordenadatramo',
            constraint=models.CheckConstraint(condition=models.Q(('longitud__gte', -180), ('longitud__lte', 180)), name='ck_coord_tramo_longitud'),
        ),
    ]
