# Generated by Django 6.0.5 on 2026-07-17 00:01

from django.db import migrations
from django.utils.dateparse import parse_datetime
from django.utils.timezone import get_current_timezone, is_naive, make_aware


def _texto(value):
    return (value or '').strip()


def _fecha(value):
    parsed = parse_datetime(_texto(value))
    if parsed and is_naive(parsed):
        return make_aware(parsed, get_current_timezone())
    return parsed


def poblar_relaciones(apps, schema_editor):
    HubSite = apps.get_model('mapas', 'HubSite')
    SalaTecnica = apps.get_model('mapas', 'SalaTecnica')
    RackFisico = apps.get_model('mapas', 'RackFisico')
    InventarioODF = apps.get_model('mapas', 'InventarioODF')
    DetallePuertoODF = apps.get_model('mapas', 'DetallePuertoODF')
    CoordenadaRuta = apps.get_model('mapas', 'CoordenadaRuta')
    InventarioTramo = apps.get_model('mapas', 'InventarioTramo')
    Ruta = apps.get_model('mapas', 'Ruta')
    IDRuta = apps.get_model('mapas', 'IDRuta')
    AlarmaVeex = apps.get_model('mapas', 'AlarmaVeex')
    EventLog = apps.get_model('mapas', 'EventLog')
    TrazaOnDemand = apps.get_model('mapas', 'TrazaOnDemand')

    errores = []
    ubicaciones = set()
    for odf in InventarioODF.objects.all().order_by('pk'):
        hub_nombre = _texto(odf.hub_site)
        sala_nombre = _texto(odf.sala)
        rack_nombre = _texto(odf.rack)
        odf_nombre = _texto(odf.odf)
        if not all((hub_nombre, sala_nombre, rack_nombre, odf_nombre)):
            errores.append(f'ODF {odf.pk}: ubicación incompleta')
            continue
        clave = (hub_nombre.casefold(), sala_nombre.casefold(), rack_nombre.casefold(), odf_nombre.casefold())
        if clave in ubicaciones:
            errores.append(f'ODF {odf.pk}: ubicación/nombre duplicado')
            continue
        ubicaciones.add(clave)

        hub = HubSite.objects.filter(nombre__iexact=hub_nombre).first()
        if not hub:
            hub = HubSite.objects.create(nombre=hub_nombre)
        sala, _ = SalaTecnica.objects.get_or_create(hub_site=hub, nombre=sala_nombre)
        rack, _ = RackFisico.objects.get_or_create(sala=sala, nombre=rack_nombre)
        InventarioODF.objects.filter(pk=odf.pk).update(rack_obj=rack)

    for puerto in DetallePuertoODF.objects.select_related('odf_obj').all().order_by('pk'):
        odf_obj = puerto.odf_obj
        if not odf_obj:
            candidatos = list(InventarioODF.objects.filter(odf__iexact=_texto(puerto.odf))[:2])
            if len(candidatos) != 1:
                errores.append(f'Puerto {puerto.pk}: ODF inexistente o ambiguo')
                continue
            odf_obj = candidatos[0]
        DetallePuertoODF.objects.filter(pk=puerto.pk).update(
            odf_obj=odf_obj,
            odf=odf_obj.odf,
        )

    tramos = {
        (tramo.ruta_id, tramo.tramo_secuencia): tramo.pk
        for tramo in InventarioTramo.objects.all()
    }
    for coordenada in CoordenadaRuta.objects.filter(tramo__isnull=True).exclude(tramo_secuencia__isnull=True):
        tramo_id = tramos.get((coordenada.ruta_id, coordenada.tramo_secuencia))
        if tramo_id:
            CoordenadaRuta.objects.filter(pk=coordenada.pk).update(tramo_id=tramo_id)
        else:
            errores.append(f'Coordenada {coordenada.pk}: tramo inexistente')

    rutas = {ruta.nombre.casefold(): ruta.pk for ruta in Ruta.objects.all()}
    for item in IDRuta.objects.filter(ruta_obj__isnull=True):
        ruta_id = rutas.get(_texto(item.ruta).casefold())
        if ruta_id:
            IDRuta.objects.filter(pk=item.pk).update(ruta_obj_id=ruta_id)
        else:
            errores.append(f'IDRuta {item.pk}: ruta inexistente')

    for Model in (AlarmaVeex, EventLog, TrazaOnDemand):
        for item in Model.objects.all().iterator():
            cambios = {}
            ruta_id = rutas.get(_texto(item.route_name).casefold())
            if ruta_id:
                cambios['ruta_obj_id'] = ruta_id
            if hasattr(item, 'timestamp'):
                timestamp_evento = _fecha(item.timestamp)
                if timestamp_evento:
                    cambios['timestamp_evento'] = timestamp_evento
            if cambios:
                Model.objects.filter(pk=item.pk).update(**cambios)

    if errores:
        muestra = '; '.join(errores[:20])
        raise RuntimeError(
            f'No se puede completar la normalización: {len(errores)} problema(s). {muestra}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0016_cablefibra_coordenadatramo_elementoplantaexterna_and_more'),
    ]

    operations = [
        migrations.RunPython(poblar_relaciones, migrations.RunPython.noop),
    ]
