# Generated by Django 6.0.5 on 2026-07-17 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0017_backfill_relaciones_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepuertoodf',
            name='odf_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puertos_detalle', to='mapas.inventarioodf', verbose_name='ODF Asociado'),
        ),
        migrations.AlterField(
            model_name='inventarioodf',
            name='rack_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odfs', to='mapas.rackfisico', verbose_name='Rack relacionado'),
        ),
    ]
