# Generated by Django 6.0.5 on 2026-07-17 00:19

from django.db import migrations


def crear_tablas_otdr_faltantes(apps, schema_editor):
    """RC1 declaraba estas tablas como unmanaged y dependía de SQL manual roto."""
    existentes = set(schema_editor.connection.introspection.table_names())
    for nombre_modelo in ('Medicion', 'PruebaOTDR', 'EventoOTDRDetalle'):
        modelo = apps.get_model('mapas', nombre_modelo)
        if modelo._meta.db_table not in existentes:
            schema_editor.create_model(modelo)
            existentes.add(modelo._meta.db_table)


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0018_alter_detallepuertoodf_odf_obj_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_tablas_otdr_faltantes, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='eventootdrdetalle',
            options={'managed': True, 'verbose_name': 'Evento OTDR Detalle', 'verbose_name_plural': 'Eventos OTDR Detalle'},
        ),
        migrations.AlterModelOptions(
            name='medicion',
            options={'managed': True, 'verbose_name': 'Medición OTDR', 'verbose_name_plural': 'Mediciones OTDR'},
        ),
        migrations.AlterModelOptions(
            name='pruebaotdr',
            options={'managed': True, 'verbose_name': 'Prueba OTDR', 'verbose_name_plural': 'Pruebas OTDR'},
        ),
    ]
