# Generated by Django 6.0.5 on 2026-07-17 00:20

import django.db.models.deletion
from django.db import migrations, models


def agregar_fk_prueba_si_falta(apps, schema_editor):
    tabla = 'mon_otdr_eventos'
    with schema_editor.connection.cursor() as cursor:
        columnas = {
            columna.name
            for columna in schema_editor.connection.introspection.get_table_description(cursor, tabla)
        }
    if 'prueba_id' not in columnas:
        # La clase actual contiene el campo que RC1 omitió de su estado de migraciones.
        from mapas.models import EventoOTDRDetalle
        schema_editor.add_field(
            EventoOTDRDetalle,
            EventoOTDRDetalle._meta.get_field('prueba'),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0019_alter_eventootdrdetalle_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(agregar_fk_prueba_si_falta, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='eventootdrdetalle',
                    name='prueba',
                    field=models.ForeignKey(blank=True, db_column='prueba_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mapas.pruebaotdr'),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='eventootdrdetalle',
            index=models.Index(fields=['node'], name='ix_evento_det_node'),
        ),
        migrations.AddIndex(
            model_name='eventootdrdetalle',
            index=models.Index(fields=['prueba', 'event_id'], name='ix_evento_det_prueba'),
        ),
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['link_internal_key'], name='ix_medicion_link_key'),
        ),
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['node', '-acquisition_date'], name='ix_medicion_node_fecha'),
        ),
        migrations.AddIndex(
            model_name='pruebaotdr',
            index=models.Index(fields=['internal_key'], name='ix_prueba_internal_key'),
        ),
        migrations.AddIndex(
            model_name='pruebaotdr',
            index=models.Index(fields=['fecha_adquisicion'], name='ix_prueba_fecha'),
        ),
    ]
