# Generated by Django 6.0.5 on 2026-07-17 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0020_eventootdrdetalle_prueba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='otu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='mapas.otu', verbose_name='OTU Asociado'),
        ),
    ]
