# Generated by Django 6.0.5 on 2026-07-17

import django.db.models.deletion
from django.db import migrations, models


def comprobar_estructura_duplicada_vacia(apps, schema_editor):
    """Evita descartar registros creados manualmente en la propuesta anterior."""

    modelos = (
        ('CableFibra', apps.get_model('mapas', 'CableFibra')),
        ('TramoCable', apps.get_model('mapas', 'TramoCable')),
        ('CoordenadaTramo', apps.get_model('mapas', 'CoordenadaTramo')),
        ('FibraCable', apps.get_model('mapas', 'FibraCable')),
    )
    ocupadas = {
        nombre: modelo.objects.count()
        for nombre, modelo in modelos
        if modelo.objects.exists()
    }
    if ocupadas:
        detalle = ', '.join(f'{nombre}={cantidad}' for nombre, cantidad in ocupadas.items())
        raise RuntimeError(
            'No se eliminaron las tablas duplicadas porque contienen registros '
            f'creados fuera de los importadores RC1/V5 ({detalle}). Exporte o concilie '
            'esos registros con Ruta, InventarioTramo e InventarioFibra antes de reintentar.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0021_alter_ruta_otu'),
    ]

    operations = [
        migrations.RunPython(
            comprobar_estructura_duplicada_vacia,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='cablefibra',
            name='ck_cable_capacidad_positiva',
        ),
        migrations.RemoveConstraint(
            model_name='cablefibra',
            name='ck_cable_longitud_no_negativa',
        ),
        migrations.RemoveConstraint(
            model_name='coordenadatramo',
            name='uq_coord_tramo_orden',
        ),
        migrations.RemoveConstraint(
            model_name='coordenadatramo',
            name='ck_coord_tramo_latitud',
        ),
        migrations.RemoveConstraint(
            model_name='coordenadatramo',
            name='ck_coord_tramo_longitud',
        ),
        migrations.RemoveConstraint(
            model_name='fibracable',
            name='uq_fibra_cable_numero',
        ),
        migrations.RemoveConstraint(
            model_name='fibracable',
            name='ck_fibra_numero_positivo',
        ),
        migrations.AlterField(
            model_name='empalmefibra',
            name='fibra_entrada',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='empalmes_entrada',
                to='mapas.inventariofibra',
            ),
        ),
        migrations.AlterField(
            model_name='terminacionfibra',
            name='fibra',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='terminaciones',
                to='mapas.inventariofibra',
            ),
        ),
        migrations.AlterField(
            model_name='empalmefibra',
            name='fibra_salida',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='empalmes_salida',
                to='mapas.inventariofibra',
            ),
        ),
        migrations.RemoveField(
            model_name='inventariofibra',
            name='fibra_fisica',
        ),
        migrations.RemoveConstraint(
            model_name='tramocable',
            name='uq_tramo_cable_secuencia',
        ),
        migrations.RemoveConstraint(
            model_name='tramocable',
            name='ck_tramo_cable_distancia',
        ),
        migrations.AlterField(
            model_name='elementoplantaexterna',
            name='tramo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='elementos_planta',
                to='mapas.inventariotramo',
            ),
        ),
        migrations.AddField(
            model_name='inventariotramo',
            name='lote_importacion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tramos_inventario',
                to='mapas.loteimportacion',
            ),
        ),
        migrations.RemoveField(
            model_name='cablefibra',
            name='destino_site',
        ),
        migrations.RemoveField(
            model_name='cablefibra',
            name='lote_importacion',
        ),
        migrations.RemoveField(
            model_name='cablefibra',
            name='origen_site',
        ),
        migrations.RemoveField(
            model_name='cablefibra',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='fibracable',
            name='cable',
        ),
        migrations.RemoveField(
            model_name='fibracable',
            name='lote_importacion',
        ),
        migrations.RemoveField(
            model_name='tramocable',
            name='cable',
        ),
        migrations.RemoveField(
            model_name='tramocable',
            name='destino_site',
        ),
        migrations.RemoveField(
            model_name='tramocable',
            name='inventario_tramo_legacy',
        ),
        migrations.RemoveField(
            model_name='tramocable',
            name='lote_importacion',
        ),
        migrations.RemoveField(
            model_name='tramocable',
            name='origen_site',
        ),
        migrations.DeleteModel(
            name='CoordenadaTramo',
        ),
        migrations.DeleteModel(
            name='FibraCable',
        ),
        migrations.DeleteModel(
            name='CableFibra',
        ),
        migrations.DeleteModel(
            name='TramoCable',
        ),
    ]
