# Generated by Django 6.0.7 on 2026-07-29 21:26

from django.db import migrations, models


def migrar_datos_globales_a_ruta(apps, schema_editor):
    Ruta = apps.get_model('mapas', 'Ruta')
    InventarioTramo = apps.get_model('mapas', 'InventarioTramo')
    InventarioFibra = apps.get_model('mapas', 'InventarioFibra')

    for ruta in Ruta.objects.all().iterator():
        tramos = list(
            InventarioTramo.objects.filter(ruta_id=ruta.pk, vigente=True)
            .order_by('tramo_secuencia', 'id')
        )
        if not tramos:
            continue

        primero = tramos[0]
        ultimo = tramos[-1]
        ruta.estado = primero.estado
        ruta.tipo_fibra = primero.tipo_fibra
        ruta.origen = primero.origen
        ruta.destino = ultimo.destino or primero.destino
        ruta.hub_site = primero.hub_site
        ruta.marca_modelo = primero.marca_modelo
        ruta.serial = primero.serial
        ruta.odf_nombre = primero.odf_nombre
        ruta.mufas = sum(tramo.mufas or 0 for tramo in tramos)
        ruta.splitters = sum(tramo.splitters or 0 for tramo in tramos)
        ruta.reservas_m = sum(tramo.reservas_m or 0 for tramo in tramos)

        fibras = InventarioFibra.objects.filter(ruta_id=ruta.pk)
        if fibras.exists():
            ruta.hilos_ocupados_declarados = fibras.filter(
                estado__in=['Ocupado', 'Ocupada', 'Activo', 'Active']
            ).count()
            ruta.hilos_libres_declarados = fibras.filter(
                estado__iexact='Libre'
            ).count()
            ruta.hilos_reservados_declarados = fibras.filter(
                estado__in=['Reservado', 'Reservada']
            ).count()
        else:
            ocupados = sum(tramo.hilos_ocupados or 0 for tramo in tramos)
            libres = sum(tramo.hilos_libres or 0 for tramo in tramos)
            if ocupados or libres:
                ruta.hilos_ocupados_declarados = ocupados
                ruta.hilos_libres_declarados = libres
                ruta.hilos_reservados_declarados = 0

        ruta.save(update_fields=[
            'estado', 'tipo_fibra', 'origen', 'destino', 'hub_site',
            'marca_modelo', 'serial', 'odf_nombre', 'mufas', 'splitters',
            'reservas_m', 'hilos_ocupados_declarados',
            'hilos_libres_declarados', 'hilos_reservados_declarados',
        ])


def devolver_datos_globales_al_primer_tramo(apps, schema_editor):
    Ruta = apps.get_model('mapas', 'Ruta')
    InventarioTramo = apps.get_model('mapas', 'InventarioTramo')

    for ruta in Ruta.objects.all().iterator():
        tramo = (
            InventarioTramo.objects.filter(ruta_id=ruta.pk, vigente=True)
            .order_by('tramo_secuencia', 'id')
            .first()
        )
        if not tramo:
            continue
        tramo.estado = ruta.estado
        tramo.capacidad = (
            f'{ruta.capacidad_hilos_declarada} Hilos'
            if ruta.capacidad_hilos_declarada is not None
            else tramo.capacidad
        )
        tramo.tipo_fibra = ruta.tipo_fibra
        tramo.origen = ruta.origen
        tramo.destino = ruta.destino
        tramo.hub_site = ruta.hub_site
        tramo.marca_modelo = ruta.marca_modelo
        tramo.serial = ruta.serial
        tramo.odf_nombre = ruta.odf_nombre
        tramo.mufas = ruta.mufas
        tramo.splitters = ruta.splitters
        tramo.reservas_m = ruta.reservas_m
        tramo.hilos_ocupados = ruta.hilos_ocupados_declarados or 0
        tramo.hilos_libres = ruta.hilos_libres_declarados or 0
        tramo.save(update_fields=[
            'estado', 'capacidad', 'tipo_fibra', 'origen', 'destino',
            'hub_site', 'marca_modelo', 'serial', 'odf_nombre', 'mufas',
            'splitters', 'reservas_m', 'hilos_ocupados', 'hilos_libres',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0028_fase1_segmentacion_tramos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='destino',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Destino declarado de la troncal'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado operativo'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='hilos_libres_declarados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hilos libres declarados'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='hilos_ocupados_declarados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hilos ocupados declarados'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='hilos_reservados_declarados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hilos reservados declarados'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='hub_site',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Hub/Site principal'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='marca_modelo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Marca / modelo del cable'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='mufas',
            field=models.PositiveIntegerField(default=0, verbose_name='Mufas totales'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='odf_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ODF declarado'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='origen',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Origen declarado de la troncal'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='reservas_m',
            field=models.FloatField(default=0.0, verbose_name='Reserva lineal total (m)'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial del cable'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='splitters',
            field=models.PositiveIntegerField(default=0, verbose_name='Splitters totales'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tipo_fibra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de fibra'),
        ),
        migrations.RunPython(
            migrar_datos_globales_a_ruta,
            reverse_code=devolver_datos_globales_al_primer_tramo,
        ),
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.CheckConstraint(
                condition=models.Q(reservas_m__gte=0),
                name='ck_ruta_reservas_m_no_negativas',
            ),
        ),
    ]
