# Generated by Django 6.0.7 on 2026-07-30 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0030_integridad_topologia_legacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariofibra',
            name='destino_nodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fibras_como_destino', to='mapas.nodored', verbose_name='Nodo final del recorrido'),
        ),
        migrations.AddField(
            model_name='inventariofibra',
            name='origen_nodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fibras_como_origen', to='mapas.nodored', verbose_name='Nodo inicial del recorrido'),
        ),
        migrations.AddField(
            model_name='inventariotramo',
            name='estado_inventario',
            field=models.CharField(choices=[('INCOMPLETO', 'Incompleto'), ('VALIDADO', 'Validado')], db_index=True, default='INCOMPLETO', max_length=20, verbose_name='Estado de completitud'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='capacidad_declarada_hilos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad oficial declarada'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='declarado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_declaradas', to=settings.AUTH_USER_MODEL, verbose_name='Declarado por'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='distancia_declarada_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Distancia oficial declarada (m)'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='fecha_declaracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de la declaración'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='fuente_declaracion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Fuente de la declaración'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='hilos_libres_declarados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hilos libres declarados'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='hilos_ocupados_declarados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hilos ocupados declarados'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='hilos_reservados_declarados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hilos reservados declarados'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='reservas_declaradas_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Reserva oficial declarada (m)'),
        ),
        migrations.AddConstraint(
            model_name='inventariofibra',
            constraint=models.CheckConstraint(condition=models.Q(('origen_nodo__isnull', True), ('destino_nodo__isnull', True), models.Q(('origen_nodo', models.F('destino_nodo')), _negated=True), _connector='OR'), name='ck_fibra_recorrido_nodos_dist'),
        ),
        migrations.AddConstraint(
            model_name='inventariotramo',
            constraint=models.CheckConstraint(condition=models.Q(('estado_inventario__in', ('INCOMPLETO', 'VALIDADO'))), name='ck_tramo_estado_inventario'),
        ),
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.CheckConstraint(condition=models.Q(('distancia_declarada_m__isnull', True), ('distancia_declarada_m__gte', 0), _connector='OR'), name='ck_ruta_dist_declarada_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad_declarada_hilos__isnull', True), ('capacidad_declarada_hilos__gt', 0), _connector='OR'), name='ck_ruta_cap_declarada_positiva'),
        ),
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.CheckConstraint(condition=models.Q(('reservas_declaradas_m__isnull', True), ('reservas_declaradas_m__gte', 0), _connector='OR'), name='ck_ruta_reserva_declarada_no_neg'),
        ),
    ]
