# Generated by Django 6.0.7 on 2026-08-17 17:11

from importlib import import_module

import django.db.models.deletion
from django.db import migrations, models


def normalizar_estados_y_contadores(apps, schema_editor):
    Fibra = apps.get_model('mapas', 'InventarioFibra')
    FibraTramo = apps.get_model('mapas', 'FibraTramo')
    Puerto = apps.get_model('mapas', 'DetallePuertoODF')
    ODF = apps.get_model('mapas', 'InventarioODF')

    estados_fibra = {
        'Libre': 'DISPONIBLE',
        'Disponible': 'DISPONIBLE',
        'Ocupado': 'OCUPADO',
        'Ocupada': 'OCUPADO',
        'Reservado': 'RESERVADO',
        'Reservada': 'RESERVADO',
        'Desconocido': 'SIN_INFORMACION',
        'Sin información': 'SIN_INFORMACION',
        'Sin informacion': 'SIN_INFORMACION',
    }
    Fibra.objects.filter(estado__iexact='Malo').update(
        estado='SIN_INFORMACION',
        origen_estado='NO_INFORMADO',
        condicion_fisica='CON_FALLA',
    )
    Fibra.objects.filter(estado__iexact='Mala').update(
        estado='SIN_INFORMACION',
        origen_estado='NO_INFORMADO',
        condicion_fisica='CON_FALLA',
    )
    for anterior, nuevo in estados_fibra.items():
        Fibra.objects.filter(estado__iexact=anterior).update(estado=nuevo)
        FibraTramo.objects.filter(estado__iexact=anterior).update(estado=nuevo)
    Fibra.objects.exclude(
        estado__in=('DISPONIBLE', 'OCUPADO', 'RESERVADO', 'SIN_INFORMACION')
    ).update(estado='SIN_INFORMACION', origen_estado='NO_INFORMADO')
    FibraTramo.objects.exclude(
        estado__in=('DISPONIBLE', 'OCUPADO', 'RESERVADO', 'SIN_INFORMACION')
    ).update(estado='SIN_INFORMACION')
    Fibra.objects.filter(
        origen_estado='NO_INFORMADO',
    ).exclude(estado='SIN_INFORMACION').update(origen_estado='INFORMADO')

    estados_puerto = {
        'Libre': 'LIBRE',
        'Disponible': 'LIBRE',
        'Ocupado': 'OCUPADO',
        'Ocupada': 'OCUPADO',
        'Reservado': 'RESERVADO',
        'Reservada': 'RESERVADO',
    }
    for anterior, nuevo in estados_puerto.items():
        Puerto.objects.filter(estado_puerto__iexact=anterior).update(
            estado_puerto=nuevo
        )
    Puerto.objects.exclude(
        estado_puerto__in=('LIBRE', 'OCUPADO', 'RESERVADO')
    ).update(estado_puerto='LIBRE')

    for odf in ODF.objects.all().iterator():
        estados = list(
            Puerto.objects.filter(odf_obj_id=odf.pk).values_list(
                'estado_puerto', flat=True
            )
        )
        ocupados = estados.count('OCUPADO')
        reservados = estados.count('RESERVADO')
        ODF.objects.filter(pk=odf.pk).update(
            puertos_ocupados=ocupados,
            puertos_reservados=reservados,
            puertos_libres=estados.count('LIBRE'),
        )


def eliminar_triggers_integridad(apps, schema_editor):
    modulo = import_module(
        'mapas.migrations.0033_integridad_fuerte_y_normalizacion_canonica'
    )
    modulo.eliminar_triggers(apps, schema_editor)


def recrear_triggers_integridad(apps, schema_editor):
    modulo = import_module(
        'mapas.migrations.0033_integridad_fuerte_y_normalizacion_canonica'
    )
    modulo.crear_triggers(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0045_codigo_fibra_estable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepuertoodf',
            options={'ordering': ['odf_obj__odf', 'puerto_odf'], 'verbose_name': 'Detalle de Puerto ODF', 'verbose_name_plural': 'Detalle de Puertos ODF'},
        ),
        migrations.RunPython(
            eliminar_triggers_integridad,
            recrear_triggers_integridad,
        ),
        migrations.RemoveConstraint(
            model_name='fibratramo',
            name='ck_fibra_tramo_estado_valido',
        ),
        migrations.RemoveConstraint(
            model_name='inventariofibra',
            name='ck_fibra_recorrido_nodos_dist',
        ),
        migrations.RemoveConstraint(
            model_name='inventariofibra',
            name='ck_inventario_fibra_estado',
        ),
        migrations.RemoveConstraint(
            model_name='inventariofibra',
            name='ck_fibra_estado_origen_coherente',
        ),
        migrations.RunPython(
            normalizar_estados_y_contadores,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='detallepuertoodf',
            name='odf',
        ),
        migrations.RemoveField(
            model_name='inventarioodf',
            name='hub_site',
        ),
        migrations.RemoveField(
            model_name='inventarioodf',
            name='rack',
        ),
        migrations.RemoveField(
            model_name='inventarioodf',
            name='sala',
        ),
        migrations.AlterField(
            model_name='auditoriafibra',
            name='accion',
            field=models.CharField(choices=[('CREAR_FIBRA', 'Crear fibra'), ('ACTUALIZAR_METADATOS', 'Actualizar metadatos'), ('CAMBIAR_ESTADO', 'Cambiar estado'), ('INFERIR_ESTADO', 'Inferir estado desde tramos'), ('RESTABLECER_ESTADO', 'Restablecer estado'), ('ASIGNAR_RUTA', 'Asignar troncal')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='detallepuertoodf',
            name='estado_puerto',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('RESERVADO', 'Reservado')], default='LIBRE', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fibratramo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('RESERVADO', 'Reservado'), ('SIN_INFORMACION', 'Sin información')], default='SIN_INFORMACION', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventariofibra',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('RESERVADO', 'Reservado'), ('SIN_INFORMACION', 'Sin información')], default='SIN_INFORMACION', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='inventariofibra',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fibras', to='mapas.loteimportacion'),
        ),
        migrations.AddConstraint(
            model_name='detallepuertoodf',
            constraint=models.CheckConstraint(condition=models.Q(('estado_puerto__in', ('LIBRE', 'OCUPADO', 'RESERVADO'))), name='ck_puerto_odf_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='fibratramo',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ('DISPONIBLE', 'OCUPADO', 'RESERVADO', 'SIN_INFORMACION'))), name='ck_fibra_tramo_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='inventariofibra',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ('DISPONIBLE', 'OCUPADO', 'RESERVADO', 'SIN_INFORMACION'))), name='ck_inventario_fibra_estado'),
        ),
        migrations.AddConstraint(
            model_name='inventariofibra',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('origen_estado', 'NO_INFORMADO'), _negated=True), ('estado', 'SIN_INFORMACION'), _connector='OR'), name='ck_fibra_estado_origen_coherente'),
        ),
        migrations.RemoveField(
            model_name='inventariofibra',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='inventariofibra',
            name='destino_nodo',
        ),
        migrations.RemoveField(
            model_name='inventariofibra',
            name='origen_nodo',
        ),
        migrations.RemoveField(
            model_name='inventariofibra',
            name='origen_odf',
        ),
        migrations.RunPython(
            recrear_triggers_integridad,
            eliminar_triggers_integridad,
        ),
    ]
