# Generated by Django 6.0.7 on 2026-09-06 02:25

import django.db.models.functions.text
from django.db import migrations, models


def comprobar_duplicados(apps, schema_editor):
    fibras = apps.get_model('mapas', 'InventarioFibra')
    duplicados = list(fibras.objects.using(schema_editor.connection.alias)
        .exclude(ruta_id=None)
        .annotate(numero=django.db.models.functions.text.Lower('fibra_numero'))
        .values('ruta_id', 'numero').annotate(total=models.Count('pk'))
        .filter(total__gt=1)[:20])
    if duplicados:
        raise RuntimeError(
            'Hay números de fibra repetidos dentro de una troncal. '
            'No se modificó ni renumeró la información. Resuelva estos conflictos antes de migrar: '
            + str(duplicados)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0047_remove_fibra_ruta_numero_unique'),
    ]

    operations = [
        migrations.RunPython(comprobar_duplicados, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='auditoriafibra',
            name='accion',
            field=models.CharField(choices=[('CREAR_FIBRA', 'Crear fibra'), ('ACTUALIZAR_METADATOS', 'Actualizar metadatos'), ('CAMBIAR_ESTADO', 'Cambiar estado'), ('INFERIR_ESTADO', 'Inferir estado desde tramos'), ('RESTABLECER_ESTADO', 'Restablecer estado'), ('ASIGNAR_RUTA', 'Asignar troncal'), ('ASIGNAR_TRAMO', 'Actualizar asignación de tramo')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditoriapuertoodf',
            name='accion',
            field=models.CharField(choices=[('CONECTAR', 'Conectar'), ('MOVER', 'Mover terminación'), ('DESCONECTAR', 'Desconectar'), ('RESERVAR', 'Reservar'), ('CANCELAR_RESERVA', 'Cancelar reserva'), ('AJUSTAR_CAPACIDAD', 'Ajustar capacidad ODF')], db_index=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='inventariofibra',
            constraint=models.UniqueConstraint(models.F('ruta'), django.db.models.functions.text.Lower('fibra_numero'), condition=models.Q(('ruta__isnull', False)), name='uq_fibra_ruta_numero_ci'),
        ),
    ]
