"""
Django settings for onmsi_mapas project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Definimos la ruta a nuestra carpeta de datos
DATA_DIR = os.path.join(BASE_DIR, 'data')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='development-only-not-for-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# Identidad y cartografía de la interfaz. Las URLs pueden apuntar a un servidor
# de teselas interno cuando el entorno operativo no tenga salida a Internet.
FIBERGENIUS_VERSION = config('FIBERGENIUS_VERSION', default='RC2 GUI 0.5.0')
FIBERGENIUS_OPERATIONS_UI_ENABLED = config(
    'FIBERGENIUS_OPERATIONS_UI_ENABLED', default=False, cast=bool
)
FIBERGENIUS_MAP_TILE_LIGHT = config(
    'FIBERGENIUS_MAP_TILE_LIGHT',
    default='https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',
)
FIBERGENIUS_MAP_TILE_DARK = config(
    'FIBERGENIUS_MAP_TILE_DARK',
    default='https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',
)
FIBERGENIUS_MAP_TILE_SATELLITE = config(
    'FIBERGENIUS_MAP_TILE_SATELLITE',
    default='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
)
FIBERGENIUS_MAP_ATTRIBUTION = config(
    'FIBERGENIUS_MAP_ATTRIBUTION',
    default='&copy; CARTO / Esri',
)

# Limites defensivos para cargas masivas. Los archivos que superen estos
# valores deben dividirse antes de importarse.
FIBERGENIUS_MAX_UPLOAD_BYTES = config(
    'FIBERGENIUS_MAX_UPLOAD_BYTES', default=25 * 1024 * 1024, cast=int
)
FIBERGENIUS_MAX_ZIP_ENTRIES = config(
    'FIBERGENIUS_MAX_ZIP_ENTRIES', default=500, cast=int
)
FIBERGENIUS_MAX_ZIP_UNCOMPRESSED_BYTES = config(
    'FIBERGENIUS_MAX_ZIP_UNCOMPRESSED_BYTES', default=100 * 1024 * 1024, cast=int
)
FIBERGENIUS_ACTIVITY_UPDATE_SECONDS = config(
    'FIBERGENIUS_ACTIVITY_UPDATE_SECONDS', default=180, cast=int
)
DATA_UPLOAD_MAX_MEMORY_SIZE = FIBERGENIUS_MAX_UPLOAD_BYTES + (1024 * 1024)
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mapas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mapas.middleware.ActiveUserMiddleware',
]

ROOT_URLCONF = 'onmsi_mapas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mapas.context_processors.fibergenius_ui',
            ],
        },
    },
]

WSGI_APPLICATION = 'onmsi_mapas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='fibergenius_bhp_prod'),
        'USER': config('DB_USER', default='fibergenius_app'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='127.0.0.1'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Configuración del idioma
LANGUAGE_CODE = "es-pe"

# Configuración de la zona horaria
TIME_ZONE = "America/Lima"

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/inventario/'
LOGOUT_REDIRECT_URL = '/login/'



# =========================
# Límites Geográficos
# =========================
GEO_BOUNDS = {
    'LAT_MIN': config('GEO_LAT_MIN', default=-60.00, cast=float),
    'LAT_MAX': config('GEO_LAT_MAX', default=-17.00, cast=float),
    'LON_MIN': config('GEO_LON_MIN', default=-76.00, cast=float),
    'LON_MAX': config('GEO_LON_MAX', default=-66.00, cast=float),
}

# Integración ONMSI. Las credenciales no tienen valores por defecto intencionalmente.
RUTA_CARPETAS_ENLACES = config('RUTA_CARPETAS_ENLACES', default=str(DATA_DIR))
MEDICIONES_API_URL = config('MEDICIONES_API_URL', default='')
MEDICIONES_API_USER = config('MEDICIONES_API_USER', default='')
MEDICIONES_API_PASSWORD = config('MEDICIONES_API_PASSWORD', default='')
EVENTOS_API_URL = config('EVENTOS_API_URL', default='')
EVENTOS_API_USER = config('EVENTOS_API_USER', default='')
EVENTOS_API_PASSWORD = config('EVENTOS_API_PASSWORD', default='')
MEDICION_INDIVIDUAL_API_URL = config('MEDICION_INDIVIDUAL_API_URL', default='')
MEDICION_INDIVIDUAL_API_USER = config('MEDICION_INDIVIDUAL_API_USER', default='')
MEDICION_INDIVIDUAL_API_PASSWORD = config('MEDICION_INDIVIDUAL_API_PASSWORD', default='')
ONMSI_TLS_VERIFY = config('ONMSI_TLS_VERIFY', default=True, cast=bool)
ONMSI_CA_BUNDLE = config('ONMSI_CA_BUNDLE', default='')


# =========================
# Logging
# =========================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'mapas': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}
